import type { z } from 'zod';
import type {
  CourseCatalog,
  PrereqGraphData,
  UserProfile,
  DegreeRequirements,
  TechCores,
  OfferingSchedule,
  MathRequirements,
  FallSections,
  SectionsIndex,
  SyllabiFile,
} from '../types';
import {
  courseCatalogSchema,
  prereqGraphSchema,
  gradeDistributionsSchema,
  degreeRequirementsSchema,
  techCoresSchema,
  offeringScheduleSchema,
  mathRequirementsSchema,
  sectionsIndexSchema,
  fallSectionsSchema,
  syllabiSchema,
} from './data-schemas';

/** Raw shape of grade-distributions.json before normalization */
export interface RawGradeDistributionsFile {
  courses: Record<string, import('../types').GradeDistribution>;
}

/**
 * Generic JSON fetcher with typed return and meaningful error messages.
 * Throws on non-2xx responses.
 *
 * When a `schema` is supplied, the parsed body is validated against it and a
 * shape mismatch throws an error that NAMES the offending file. This makes a
 * malformed / scraper-regressed data file fail loudly at load instead of
 * surfacing later as a confusing solver or progress bug.
 */
export async function fetchJson<T>(url: string, schema?: z.ZodType<T>): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load ${url}: HTTP ${response.status} ${response.statusText}`
    );
  }
  const body: unknown = await response.json();
  if (!schema) {
    return body as T;
  }
  const result = schema.safeParse(body);
  if (!result.success) {
    throw new Error(
      `Data file ${url} is malformed: ${result.error.issues
        .map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`)
        .slice(0, 5)
        .join('; ')}`
    );
  }
  return result.data;
}

// ─── Per-file loaders ────────────────────────────────────────────────────────

export function loadCourseCatalog(): Promise<CourseCatalog> {
  return fetchJson<CourseCatalog>('/data/course-catalog.json', courseCatalogSchema);
}

export function loadPrereqGraph(): Promise<PrereqGraphData> {
  return fetchJson<PrereqGraphData>('/data/prerequisite-graph.json', prereqGraphSchema);
}

export function loadRawGradeDistributions(): Promise<RawGradeDistributionsFile> {
  return fetchJson<RawGradeDistributionsFile>(
    '/data/grade-distributions.json',
    gradeDistributionsSchema
  );
}

/**
 * Load the demo profile (Adi's dataset) from /data/user-profile.json.
 * Use for the "Load demo profile" action — NOT as the runtime-default profile.
 * The runtime default is EMPTY_PROFILE in ProfileContext.
 */
export function loadDemoProfile(): Promise<UserProfile> {
  return fetchJson<UserProfile>('/data/user-profile.json');
}

export function loadDegreeRequirements(): Promise<DegreeRequirements> {
  return fetchJson<DegreeRequirements>(
    '/data/degree-requirements.json',
    degreeRequirementsSchema
  );
}

export function loadTechCores(): Promise<TechCores> {
  return fetchJson<TechCores>('/data/tech-cores.json', techCoresSchema);
}

export function loadOfferingSchedule(): Promise<OfferingSchedule> {
  return fetchJson<OfferingSchedule>('/data/offering-schedule.json', offeringScheduleSchema);
}

export function loadMathRequirements(): Promise<MathRequirements> {
  return fetchJson<MathRequirements>('/data/math-requirements.json', mathRequirementsSchema);
}

/**
 * Load the per-term sections manifest. Throws if missing — the manifest is
 * generated by `npm run fetch:sections` (see scripts/sections/README.md) and
 * is committed alongside the per-term files.
 */
export function loadSectionsIndex(): Promise<SectionsIndex> {
  return fetchJson<SectionsIndex>('/data/sections-index.json', sectionsIndexSchema);
}

/**
 * Load a single term's sections file. Resolves the filename through the
 * sections-index manifest so DataContext never hard-codes a per-term filename.
 *
 * When `termSlug` is omitted, the manifest's `default_term` is used (typically
 * the most-recently-published term).
 */
export async function loadTermSections(
  termSlug?: string
): Promise<FallSections> {
  const index = await loadSectionsIndex();
  const slug = termSlug ?? index.default_term;
  const entry = index.terms.find((t) => t.slug === slug);
  if (!entry) {
    throw new Error(
      `Term "${slug}" not found in sections-index.json. ` +
        `Available terms: ${index.terms.map((t) => t.slug).join(', ') || '(none)'}. ` +
        `Run \`npm run fetch:sections -- ${slug}\` to generate it.`
    );
  }
  return fetchJson<FallSections>(`/data/${entry.file}`, fallSectionsSchema);
}

/**
 * Backward-compatible alias for the default term's sections.
 * Existing call sites (SchedulerPage, CourseDetailDialog) keep working.
 */
export function loadFallSections(): Promise<FallSections> {
  return loadTermSections();
}

/**
 * Load the scraped past-syllabus enrichment data.
 * This is non-core enrichment: callers should catch errors gracefully
 * rather than letting a syllabi failure surface as an app error.
 */
export function loadSyllabi(): Promise<SyllabiFile> {
  return fetchJson<SyllabiFile>('/data/syllabi.json', syllabiSchema);
}
